const words = [
  { id: "1", en: "abandon", mn: '"орхих явах' },
  { id: "2", en: "adversely", mn: "сөрөгөөр" },
  { id: "3", en: "aggregate", mn: 'v"' },
  { id: "4", en: "cultivation", mn: "тариалалт" },
  { id: "5", en: "fertilize", mn: "бордох" },
  { id: "6", en: "intensify", mn: "эрчимжүүлэх" },
  { id: "7", en: "irrigation", mn: "усжуулалт" },
  { id: "8", en: "obtain", mn: '"олж авах' },
  { id: "9", en: "photosynthesis", mn: "фотосинтез" },
  { id: "10", en: "precipitation", mn: "хур тунадас" },
  { id: "11", en: "anticipate", mn: '"урьдаас мэдэх' },
  { id: "12", en: "flood", mn: "үер" },
  { id: "13", en: "catastrophic", mn: "сүйрлийн" },
  { id: "14", en: "impact", mn: '"нөлөө' },
  { id: "15", en: "collide", mn: "мөргөлдөх" },
  { id: "16", en: "persevere", mn: "цөхрөлтгүй зүтгэх" },
  { id: "17", en: "eruption", mn: "дэлбэрэлт" },
  { id: "18", en: "plunge", mn: "шумбах доошлох" },
  { id: "19", en: "famine", mn: "өлсгөлөн" },
  { id: "20", en: "unleash", mn: '"cуллах' },
  { id: "21", en: "adapt", mn: '"дасах зохицох' },
  { id: "22", en: "inherent", mn: '"угийн' },
  { id: "23", en: "diverse", mn: '"төрөл бүрийн' },
  { id: "24", en: "migration", mn: '"нүүдэл' },
  { id: "25", en: "evolve", mn: '"боловсруулах' },
  { id: "26", en: "physical", mn: "биеийн" },
  { id: "27", en: "feature", mn: "онцлог шинж" },
  { id: "28", en: "process", mn: "үйл явц" },
  { id: "29", en: "generation", mn: "үе" },
  { id: "30", en: "survive", mn: '"амьд үлдэх' },
  { id: "31", en: "constraint", mn: "хязгаарлалт" },
  { id: "32", en: "emission", mn: "ялгаруулалт" },
  { id: "33", en: "contamination", mn: "бохирдол" },
  { id: "34", en: "extinction", mn: "мөхөл" },
  { id: "35", en: "deplete", mn: "багасгах хорогдох" },
  { id: "36", en: "reservoir", mn: "усан сан" },
  { id: "37", en: "dispose of", mn: '"салгах' },
  { id: "38", en: "shrink", mn: "агших" },
  { id: "39", en: "elementally", mn: "үндсэндээ" },
  { id: "40", en: "stable", mn: '"бат' },
  { id: "41", en: "adjust", mn: '"тохируулах' },
  { id: "42", en: "maximize", mn: "хамгийн их болгох" },
  { id: "43", en: "arbitrary", mn: "дур зоргоороо" },
  { id: "44", en: "parallel", mn: "зэрэгцээ" },
  { id: "45", en: "denominator", mn: "хуваарь" },
  { id: "46", en: "proportion", mn: " харьцаа" },
  { id: "47", en: "exponentially", mn: '"огцом' },
  { id: "48", en: "rate", mn: '"хурд' },
  { id: "49", en: "infinitesimal", mn: "маш жижигхэн" },
  { id: "50", en: "sequence", mn: "дэс дараалалд оруулах" },
  { id: "51", en: "accuracy", mn: "нарийвчлал" },
  { id: "52", en: "integrally", mn: '"бүхлээр нь' },
  { id: "53", en: "adjacent", mn: '"зэрэгцээ' },
  { id: "54", en: "overlap", mn: '"давхцах' },
  { id: "55", en: "compress", mn: '"шахах' },
  { id: "56", en: "retain", mn: '"хадгалж үлдэх' },
  { id: "57", en: "feasibly", mn: "хэрэгжиж болохуйц" },
  { id: "58", en: "seep", mn: '"нэвчих' },
  { id: "59", en: "gut", mn: "хоослох" },
  { id: "60", en: "structure", mn: '"бүтэц' },
  { id: "61", en: "circulate", mn: '"тойрох' },
  { id: "62", en: "implement", mn: "хэрэгжүүлэх" },
  { id: "63", en: "corrode", mn: "зэврэх" },
  { id: "64", en: "innovative", mn: "шинийг сэдсэн санаачилсан" },
  { id: "65", en: "derive", mn: "гарган авах" },
  { id: "66", en: "installation", mn: " суурилуулалт" },
  { id: "67", en: "detection", mn: "илрүүлэлт" },
  { id: "68", en: "maintenance", mn: "арчилгаа" },
  { id: "69", en: "expeditiously", mn: '"хурданаар' },
  { id: "70", en: "simulation", mn: '"дууриалгалт' },
  { id: "71", en: "combustion", mn: "дотоод шаталт" },
  { id: "72", en: "permeate", mn: '"нэвчих' },
  { id: "73", en: "component", mn: "бүрэлдэхүүн хэсэг" },
  { id: "74", en: "rotate", mn: "эргэх" },
  { id: "75", en: "convey", mn: "дамжуулах" },
  { id: "76", en: "solar", mn: "нарны" },
  { id: "77", en: "discretely", mn: '"тусдаа' },
  { id: "78", en: "source", mn: "эх сурвалж" },
  { id: "79", en: "nucleus", mn: "цөм" },
  { id: "80", en: "trigger", mn: '"эхлүүлэх' },
  { id: "81", en: "acquisition", mn: '"авалт' },
  { id: "82", en: "indisputable", mn: "маргаангүй" },
  { id: "83", en: "anomaly", mn: '"гажиг' },
  { id: "84", en: "intervene", mn: "хөндлөнгөөс оролцох" },
  { id: "85", en: "consciously", mn: "санаатайгаар" },
  { id: "86", en: "intuitively", mn: " зөн совингоороо" },
  { id: "87", en: "degrade", mn: '"дордуулах' },
  { id: "88", en: "recede", mn: '"алсрах' },
  { id: "89", en: "gap", mn: "завсар" },
  { id: "90", en: "retrieve", mn: "буцааж авчрах" },
  { id: "91", en: "agnostic", mn: '"танин мэдэхүйг үгүйсгэгч' },
  { id: "92", en: "deify", mn: "бурханчлан шүтэх" },
  {
    id: "93",
    en: "animism",
    mn: "Байгаль дахь бүх зүйлс  сүнстэй гэж үздэг үзэл",
  },
  { id: "94", en: "ecclesiastical", mn: '"шашны' },
  { id: "95", en: "atheist", mn: "шүтлэггүй хүн" },
  { id: "96", en: "exalt", mn: "өндөрт өргөн магтах" },
  { id: "97", en: "be inclined to", mn: "хандлагатай байх" },
  { id: "98", en: "pious", mn: "сүсэгтэй" },
  { id: "99", en: "contemplate", mn: "эргэцүүлэн бодох" },

];
